name: Builds

on:
  push: { branches: [main] }
  pull_request:
    paths-ignore:
      - '.github/**'

     

jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
   
    steps:

      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v2
        with:
         lfs: true

     
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
     
      - name: Install NDK
        run:  echo "y" | wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip
              #sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;19.2.5345600" --sdk_root=${ANDROID_SDK_ROOT}
      - name: ZIP INSTALL
        run: sudo apt-get install p7zip-full 
      - name: UNZIP NDK
        run: unzip android-ndk-r19c-linux-x86_64.zip
        #sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;19.2.5345600" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Output version code
        run: echo VERSION_CODE=${{ github.run_number }} > ./version.properties
      - name: Info
        run: |  
              sh ./info.sh
              
 
