name: Builds

on:
  push: { branches: [main] }
  pull_request:
    paths-ignore:
      - '.github/**'

     

jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
   
    steps:

      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v2
        with:
         lfs: true

     
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
     
      - name: Install NDK
        run:  echo "y" | wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip
              #sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;19.2.5345600" --sdk_root=${ANDROID_SDK_ROOT}
      - name: ZIP INSTALL
        run: sudo apt-get install p7zip-full 
      - name: UNZIP NDK
        run: unzip android-ndk-r19c-linux-x86_64.zip
        #sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;19.2.5345600" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Output version code
        run: echo VERSION_CODE=${{ github.run_number }} > ./version.properties
      
      - name: Build with Gradle
        run: |
          sudo gradle wrapper --gradle-version 5.6.4 --stacktrace 
          echo "=================gradle wrappe======================="
          sudo chmod +x ./gradlew
          echo "====================chmod +x ./gradlew===================="
          sudo ./gradlew init
          echo "====================chmod +x ./gradlew===================="
          sudo ./gradlew clean
          echo "====================./gradlew init===================="
          sudo ./gradlew test
          echo "======================./gradlew test=================="
          sudo ./gradlew bundleRelease
          echo "=======================./gradlew bundleRelease================="
          sudo ./gradlew assembleRelease 
          echo "======================./gradlew assembleRelease=================="      
      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: /home/runner/work/testing/testing/launcher/build/outputs/apk/release
